### ISSUE TITLE
Move this repository in the `ralna` organization?

### ISSUE THREAD

**Issue by amontoison** [ralna/JuliaHSL#2]
@jfowkes
https://github.com/ralna

It's the dummy version that I will precompile with Yggdrasil.

**Comment by jfowkes** [comment]
Good question, I will ask at our meeting on Monday.

**Comment by amontoison** [comment]
@jfowkes You can move the repository to the `ralna` organization. I changed the license.

**Comment by jfowkes** [comment]
@amontoison you need to give me owner access otherwise I can't move the repo.
